Exception in Java
cristescudaniela/test_automation_course pull request #5
Opened 2023-03-05 18:22 UTC by cristescudaniela

2023-03-09 07:06 UTC, dmitryturcan requested changes

2023-03-09 07:06 UTC, dmitryturcan commented on topic6/ContulPersoanei.java
> +package topic6;
sugerez sa mai arunci un alt tip de exceptie, de ex IllegalArgumentException, sau NullPointerException in caz ca transmiti o valoare null unde este asteptat sa fie ceva, in sarrcina prarctica era specificat sa ai mai multe tipurri de exceptii, in rest Bravo!

2023-03-09 07:06 UTC, dmitryturcan commented on topic6/Main.java
> +package topic6;
sugerezi sa adaugi crearea unui obiect sau a unei operratiuni care trebuie sa arunce exceptie, si sa o prrinzi iar dupa sa o fixezi

2023-03-13 21:43 UTC, vcelpan commented
The exception has been added successfully.

2023-03-13 21:49 UTC, vcelpan approved these changes

2023-03-18 21:54 UTC, dmitryturcan approved these changes

2023-03-21 13:35 UTC, merged